calib_beamshift:
  gridsize: 5
  stepsize: 2500
calib_directbeam:
  BeamShift:
    gridsize: 5
    stepsize: 350
  DiffShift:
    gridsize: 5
    stepsize: 1500
camera_rotation_vs_stage_xy: 0.0
default_binsize: 2
default_exposure: 0.1
dimensions: [2048, 2048]
interface: simulateDLL
possible_binsizes: [1, 2, 4]
stretch_amplitude: 0
stretch_azimuth: 0
dead_time: 0.0
