calib_beamshift:
  gridsize: 5
  stepsize: 500
calib_directbeam:
  BeamShift:
    gridsize: 5
    stepsize: 75
  DiffShift:
    gridsize: 5
    stepsize: 300
camera_rotation_vs_stage_xy: -0.017
default_binsize: 2
default_exposure: 0.4
dimensions: [4096, 4096]
dynamic_range: 65535
interface: emmenu
physical_pixelsize: 0.0156
possible_binsizes: [1, 2, 4]
stretch_amplitude: 0.0
stretch_azimuth: 0.0
