name: simulate
diff:
  pixelsize:
    150: 0.00838
    200: 0.00623
    250: 0.00499
    300: 0.00412
    400: 0.00296
    500: 0.00238
    600: 0.00198
    800: 0.00148
lowmag:
  pixelsize:
    -1: -1
  stagematrix:
    -1: []
mag1:
  pixelsize:
    2500: 11.54651
    3000: 9.49031
    4000: 6.99806
    5000: 5.54069
    6000: 4.5872
    8000: 3.41085
    10000: 2.7655
    12000: 2.32364
    15000: 1.87596
    20000: 1.4186
    25000: 1.14147
    30000: 0.96511
    40000: 0.72286
    50000: 0.57751
    60000: 0.48255
    80000: 0.36046
    100000: 0.28875
    120000: 0.24031
    150000: 0.19186
    200000: 0.14341
    250000: 0.11434
    300000: 0.09496
    400000: 0.0717
    500000: 0.0562
    600000: 0.04651
    800000: 0.03488
    1000000: 0.02713
    1500000: 0.01744
    2000000: 0.01356
  stagematrix:
    2500: [1, 0, 0, 1]
    3000: [1, 0, 0, 1]
    4000: [1, 0, 0, 1]
    5000: [1, 0, 0, 1]
    6000: [1, 0, 0, 1]
    8000: [1, 0, 0, 1]
    10000: [1, 0, 0, 1]
    12000: [1, 0, 0, 1]
    15000: [1, 0, 0, 1]
    20000: [1, 0, 0, 1]
    25000: [1, 0, 0, 1]
    30000: [1, 0, 0, 1]
    40000: [1, 0, 0, 1]
    50000: [1, 0, 0, 1]
    60000: [1, 0, 0, 1]
    80000: [1, 0, 0, 1]
    100000: [1, 0, 0, 1]
    120000: [1, 0, 0, 1]
    150000: [1, 0, 0, 1]
    200000: [1, 0, 0, 1]
    250000: [1, 0, 0, 1]
    300000: [1, 0, 0, 1]
    400000: [1, 0, 0, 1]
    500000: [1, 0, 0, 1]
    600000: [1, 0, 0, 1]
    800000: [1, 0, 0, 1]
    1000000: [1, 0, 0, 1]
    1500000: [1, 0, 0, 1]
    2000000: [1, 0, 0, 1]
