name: F416
diff:
  pixelsize:
    15: 0.0026859
    20: 0.0018867
    30: 0.0012304
    40: 0.0009104
    50: 0.0007115
    60: 0.000584
    80: 0.0004292
    100: 0.0003374
    120: 0.0002801
lowmag:
  flipud: true
  fliplr: false
  rot90:
    250: -1
    300: -1
    400: -1
    500: -1
    600: -1
    800: -1
    1000: -1
  pixelsize:
    10: 1.0
    15: 1.0
    20: 1.0
    25: 1.0
    30: 1.0
    40: 305.2
    50: 227.9
    60: 195.8
    80: 145.6
    100: 115.6
    150: 77.71
    200: 59.31
    250: 45.36
    300: 37.6
    400: 27.94
    500: 22.18
    600: 19.65
    800: 14.52
    1000: 11.31
  stagematrix:
    100: [-111.6049, 0.5053, -0.482, -117.0024]
    150: [-74.9815, 1.7568, -1.6853, -78.1632]
    200: [-56.8424, 2.5015, -2.4034, -59.1638]
    250: [-43.9488, -1.3013, 1.2655, -45.1904]
    300: [-36.6363, -1.4564, 1.4212, -37.5442]
    400: [-27.3828, -0.8875, 0.8714, -27.8909]
    500: [-21.7713, -0.6902, 0.6799, -22.1014]
    600: [-18.4797, -0.6007, 0.5936, -18.7025]
    800: [-13.8946, -0.4251, 0.4214, -14.0162]
    1000: [-10.9874, -0.2058, 0.2048, -11.0408]
mag1:
  flipud: true
  fliplr: false
  pixelsize:
    200: 44.7
    250: 38.69
    300: 34.19
    400: 26.36
    500: 22.18
    600: 18.7
    800: 14.23
    1000: 11.51
    1200: 9.605
    1500: 7.663
    2000: 5.791
    2500: 4.543
    3000: 3.832
    4000: 2.848
    5000: 2.281
    6000: 1.924
    8000: 1.453
    10000: 1.165
    12000: 0.9855
    15000: 0.7711
    20000: 0.5901
    25000: 0.4809
    30000: 0.3868
    40000: 0.291
    50000: 0.2331
    60000: 0.1924
    80000: 0.1434
    100000: 0.114
    120000: 0.09363
    150000: 1.0
    200000: 1.0
    250000: 1.0
    300000: 1.0
    500000: 1.0
    600000: 1.0
    800000: 1.0
    1000000: 1.0
    1200000: 1.0
  stagematrix:
    200: [-53.5999, -0.4209, 0.4176, -54.0243]
    250: [-42.6095, -0.3531, 0.3397, -44.2983]
    300: [-35.9015, -0.5018, 0.4863, -37.0467]
    400: [-26.9955, -0.4643, 0.453, -27.6642]
    500: [-22.313, -0.4036, 0.3957, -22.7627]
    600: [-18.8277, -0.32, 0.3148, -19.1366]
    800: [-14.2596, -0.2592, 0.2553, -14.4779]
    1000: [-11.486, -0.1432, 0.1413, -11.6373]
    1200: [-9.6432, -0.1593, 0.159, -9.6568]
    1500: [-7.6711, -0.1248, 0.1246, -7.685]
    2000: [-5.8342, 0.0185, -0.0184, -5.8546]
    2500: [-4.6051, 0.0226, -0.0226, -4.6055]
