camera_rotation_vs_stage_xy: -0.672
stretch_azimuth: -6.63
stretch_amplitude: 2.43
wavelength: 0.025080
cameras: [timepix, orius, simulate]
specifications:
  CAMERALENGTHS: [150, 200, 250, 300, 400, 500, 600, 800, 1000, 1200,
    1500, 2000, 2500, 3000, 3500, 4000, 4500]
  MAGNIFICATIONS: [50, 60, 80, 100, 150, 200, 250, 300, 400, 500, 600,
    800, 1000, 1200, 1500, 2000, 2500, 3000, 4000, 5000, 6000, 8000, 10000, 12000,
    15000, 20000, 25000, 30000, 40000, 50000, 60000, 80000, 100000, 120000, 150000,
    200000, 250000, 300000, 400000, 500000, 600000, 800000, 1000000, 1200000, 1500000,
    2000000]
  MAGNIFICATION_MODES: {
    lowmag: 50, 
    mag1: 2500 }
  rotation_speeds: {
    fine: [ 0.114, 0.45, 1.126 ], 
    coarse: [ 0.45, 1.8, 4.5 ] }
timepix:
  diffraction_pixeldimensions: 
    150: 0.00838
    200: 0.00623
    250: 0.00499
    300: 0.00412
    400: 0.00296
    500: 0.00238
    600: 0.00198
    800: 0.00148
  mag1_camera_dimensions:
    2500: [5.958436571428572, 5.958436571428572]
    3000: [4.8972434285714295, 4.8972434285714295]
    4000: [3.611022628571429, 3.611022628571429]
    5000: [2.859889371428572, 2.859889371428572]
    6000: [2.3674368, 2.3674368]
    8000: [1.7609801142857142, 1.7609801142857142]
    10000: [1.4270756571428573, 1.4270756571428573]
    12000: [1.199612342857143, 1.199612342857143]
    15000: [0.9681408, 0.9681408]
    20000: [0.7325586285714286, 0.7325586285714286]
    25000: [0.5891876571428573, 0.5891876571428573]
    30000: [0.49814674285714294, 0.49814674285714294]
    40000: [0.37361005714285717, 0.37361005714285717]
    50000: [0.2988873142857143, 0.2988873142857143]
    60000: [0.24907337142857147, 0.24907337142857147]
    80000: [0.18680685714285714, 0.18680685714285714]
    100000: [0.14944548571428573, 0.14944548571428573]
    120000: [0.12453668571428574, 0.12453668571428574]
    150000: [0.09962788571428571, 0.09962788571428571]
    200000: [0.07472274285714287, 0.07472274285714287]
    250000: [0.059776, 0.059776]
    300000: [0.04981394285714286, 0.04981394285714286]
    400000: [0.03736137142857143, 0.03736137142857143]
    500000: [0.029889828571428575, 0.029889828571428575]
    600000: [0.024908800000000002, 0.024908800000000002]
    800000: [0.01868434285714286, 0.01868434285714286]
    1000000: [0.014943085714285714, 0.014943085714285714]
    1500000: [0.009962057142857144, 0.009962057142857144]
    2000000: [0.007471542857142857, 0.007471542857142857]
  lowmag_pixeldimensions:
    -1: -1
orius:
  diffraction_pixeldimensions: 
    150: 0.02942304 
    200: 0.02206728
    250: 0.017653824
    300: 0.01471152
    400: 0.01103364
    500: 0.008826912
    600: 0.00735576
    800: 0.00544891
    1000: 0.004202
    1200: 0.0036496
    1500: 0.00285546
    2000: 0.00213076
    2500: 0.00169945
    3000: 0.00141621
    3500: 0.0012139
    4000: 0.00106216
  lowmag_pixeldimensions:
    50: [0.895597, 0.895597]
    80: [0.559748, 0.559748]
    100: [0.447799, 0.447799]
    150: [0.298532, 0.298532]
    200: [0.223899, 0.223899]
    250: [0.179119, 0.179119]
    300: [0.149266, 0.149266]
    400: [0.111949, 0.111949]
    500: [0.089559, 0.089559]
    600: [0.074633, 0.074633]
    800: [0.055974, 0.055974]
    1000: [0.044779, 0.044779]
    1200: [0.037316, 0.037316]
    1500: [0.029853, 0.029853]
    2000: [0.0208, 0.0208]
    2500: [0.01664, 0.01664]
    3000: [0.013866, 0.013866]
    5000: [0.00832, 0.00832]
    6000: [0.006933, 0.006933]
    8000: [0.0052, 0.0052]
    10000: [0.00416, 0.00416]
    12000: [0.003466, 0.003466]
    15000: [0.002773, 0.002773]
  mag1_camera_dimensions:
    2500: [33.3672448, 33.3672448]
    3000: [27.4245632, 27.4245632]
    4000: [20.22172672, 20.22172672]
    5000: [16.01538048, 16.01538048]
    6000: [13.25764608, 13.25764608]
    8000: [9.86148864, 9.86148864]
    10000: [7.99162368, 7.99162368]
    12000: [6.71782912, 6.71782912]
    15000: [5.42158848, 5.42158848]
    20000: [4.10232832, 4.10232832]
    25000: [3.29945088, 3.29945088]
    30000: [2.78962176, 2.78962176]
    40000: [2.09221632, 2.09221632]
    50000: [1.67376896, 1.67376896]
    60000: [1.39481088, 1.39481088]
    80000: [1.0461184, 1.0461184]
    100000: [0.83689472, 0.83689472]
    120000: [0.69740544, 0.69740544]
    150000: [0.55791616, 0.55791616]
    200000: [0.41844736, 0.41844736]
    250000: [0.3347456, 0.3347456]
    300000: [0.27895808, 0.27895808]
    400000: [0.20922368, 0.20922368]
    500000: [0.16738304, 0.16738304]
    600000: [0.13948928, 0.13948928]
    800000: [0.10463232, 0.10463232]
    1000000: [0.08368128, 0.08368128]
    1500000: [0.05578752, 0.05578752]
    2000000: [0.04184064, 0.04184064]
simulate:
  diffraction_pixeldimensions: 
    150: 0.0087
    200: 0.0065
    250: 0.0052
    300: 0.0043
    400: 0.0032
    500: 0.0026
  mag1_camera_dimensions:
    2500: [5.958, 5.958]
    3000: [4.897, 4.897]
    4000: [3.611, 3.611]
    5000: [2.859, 2.859]
    6000: [2.367, 2.367]
    8000: [1.760, 1.760]
    10000: [1.427, 1.427]
    12000: [1.199, 1.199]
    15000: [0.968, 0.968]
    20000: [0.732, 0.732]
    25000: [0.589, 0.589]
    30000: [0.498, 0.498]
    40000: [0.373, 0.373]
    50000: [0.298, 0.298]
    60000: [0.249, 0.249]
    80000: [0.186, 0.186]
    100000: [0.149, 0.149]
    120000: [0.124, 0.124]
    150000: [0.099, 0.099]
    200000: [0.074, 0.074]
    250000: [0.059, 0.059]
    300000: [0.049, 0.049]
    400000: [0.037, 0.037]
    500000: [0.029, 0.029]
    600000: [0.024, 0.024]
    800000: [0.018, 0.018]
    1000000: [0.014, 0.014]
    1500000: [0.009, 0.009]
    2000000: [0.007, 0.007]
  lowmag_pixeldimensions:
    -1: -1