gridmontage:
  gridspec:
    direction: 'downup'
    zigzag: true
    flip: true
  overlap: 0.1
montage:
  from_serialem_mrc:
    direction: 'downup'
    zigzag: true
    flip: true
    rot90: 3
    flipud: true
    fliplr: false
